# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'


development:
  adapter: mysql2
  database: depot_development
  encoding: utf8
  host: 127.0.0.1
  pool: 5
  username: root
  password:
  timeout: 5000